# Generated by Django 5.0.1 on 2024-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_mitem_user_delete_mitem_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitem",
            name="details",
            field=models.TextField(default="Default details"),
        ),
    ]
