# Generated by Django 5.0.1 on 2024-02-28 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_mitem_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mitem",
            name="details",
        ),
    ]
