# Generated by Django 5.0.1 on 2024-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_remove_mitem_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="mitem",
            name="details",
            field=models.TextField(default="{}"),
        ),
    ]
