# Generated by Django 5.0.1 on 2024-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_mitem_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mitem",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
