# Generated by Django 5.0.1 on 2024-03-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_mitem_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="addeditem",
            name="url",
            field=models.URLField(default=""),
        ),
    ]
