# Generated by Django 5.0.1 on 2024-03-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_addeditem_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addeditem",
            old_name="url",
            new_name="href",
        ),
        migrations.AddField(
            model_name="customnavigationitem",
            name="href",
            field=models.URLField(default=""),
        ),
    ]
