# Generated by Django 5.0.1 on 2024-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_url_addeditem_href_customnavigationitem_href"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
    ]
