# Generated by Django 5.0.4 on 2024-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploadmodel",
            name="file",
            field=models.BinaryField(),
        ),
    ]
