# Generated by Django 5.0.4 on 2024-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_userprofile_otp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadmodel",
            name="file_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
