# Generated by Django 5.0.4 on 2024-05-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_fileuploadmodel_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileuploadmodel",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
