# Generated by Django 5.0.4 on 2024-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_alter_fileuploadmodel_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileuploadmodel",
            name="file_name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="otp_secret",
            field=models.CharField(max_length=16),
        ),
    ]
