# Generated by Django 5.0.4 on 2024-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_remove_fileuploadmodel_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="otp_secret",
            field=models.CharField(max_length=200),
        ),
    ]
