# Generated by Django 5.0.4 on 2024-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_rename_patchedstatus_work_patched_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="High",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="Ministry",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="data",
            name="Patched_Status",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="work",
            name="High",
            field=models.BigIntegerField(),
        ),
    ]
